# Generated by Django 5.1.1 on 2024-09-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
