# Generated by Django 5.1.1 on 2024-09-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0012_alter_comment_options_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='parent_post',
            new_name='parent_comment',
        ),
    ]
